### ISSUE TITLE
support pin-value in pkcs11 uri 

### ISSUE THREAD

**Issue by viperomega** [caml-pkcs11/caml-crush#30]
Hi,
i try to use caml-crush with pin-value in uri. Looks like it is not working/not supported. 
pin-value is part of rfc7512.
softhsm2 is supporting pin-value.

regards

**Comment by rb-anssi** [comment]
Hi viperomega,

RFC7512 concerns the layer above the PKCS#11 API, namely the wrappers (such as pkcs11-tool from OpenSC or OpenSSL engines) that load and use PKCS#11 token libraries (such as softhsmv2).

Caml-Crush is a PKCS#11 proxy, and as such it does not handle (and does not need to handle) URIs : if you use a PKCS#11 wrapper that deals with PKCS#11 URIs, this should work seamlessly. Of course, you will have to adapt the target PKCS#11 library in the URI (i.e. put the Caml-Crush client library in place of the original one) when invoking the PKCS#11 wrapper.

Regards
