### ISSUE TITLE
pkcs11proxyd fails to start 

### ISSUE THREAD

**Issue by cdanger** [caml-pkcs11/caml-crush#56]
I tried to run caml-crush daemon on Ubuntu 20.04 LTS (Focal):

```shell
$ sudo pkcs11proxyd -fg -conf /etc/pkcs11proxyd/pkcs11proxyd.conf
```

But the program exits right away without any error message, and does not bind to local port 4444 as it is supposed to do by configuration.

I also ran it with `-debug-all` option but could not see anything wrong. You may find the debug logs in the [pkcs11proxyd.log](https://github.com/caml-pkcs11/caml-crush/files/8239955/pkcs11proxyd.log) attached.

Any idea on how I can troubleshoot this?

A bit of context: in order to install caml-crush properly, I built the debian package for Focal (amd-64) from the source package on [caml-crush PPA](https://launchpad.net/~calderon-thomas/+archive/ubuntu/caml-crush). (No binary package is available for Focal on the PPA or official mirrors unfortunately :-(. ) Before I do that, first I had to install the coccinelle dependency from [coccinelle PPA](https://launchpad.net/~npalix/+archive/ubuntu/coccinelle) because it is not available for Focal on official mirrors either :-( .

**Comment by rb-anssi** [comment]
Hi @cdanger,

On an `ubuntu/focal` docker, I have been able to launch `pkcs11proxyd` without any unexpected exit:

```
root@7f36eab49142:/caml-crush# ./src/pkcs11proxyd/pkcs11proxyd -conf /caml-crush/src/pkcs11proxyd/pkcs11proxyd.conf -fg
[Thu Mar 17 09:14:31 2022] [PKCS#11 Filtering Proxy] [info] [PKCS#11 FILTER pid 9115] [DEBUG_LEVEL 0/0] Log subchannel is: 
[Thu Mar 17 09:14:31 2022] [PKCS#11 Filtering Proxy] [info] [PKCS#11 FILTER pid 9115] [DEBUG_LEVEL 0/0] filter
[Thu Mar 17 09:14:31 2022] [PKCS#11 Filtering Proxy] [info] [PKCS#11 FILTER pid 9115] [DEBUG_LEVEL 0/0] Debug level is: 
[Thu Mar 17 09:14:31 2022] [PKCS#11 Filtering Proxy] [info] [PKCS#11 FILTER pid 9115] [DEBUG_LEVEL 0/0] 0
```

I have installed coccinelle from the PPA, but have compiled `caml-crush` from the git upstream source tree (and not from the source package PPA).
Can you please `git clone` the repository and try this?

Regards,

**Comment by rb-anssi** [comment]
Hi,

Thanks for the feedback, and sorry for the late answer.

Since Ubuntu 20.04 LTS focal has issues with coccinelle (as it is not packaged) as you have pointed out, we do not plan for now to support/release a debian package for it. Sorry about this: I guess that downgrading the dependencies, although not satisfactory, is currently the best way to go.

Regards,

**Comment by cdanger** [comment]
OK, fair enough, thanks for your reply, closing this issue.
